# Example markdown lint YAML configuration with all properties set to their default value

# Default state for all rules
default: true

# Path to configuration file to extend
extends: null

MD013: false
MD046: false
MD007: false
